#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco.Web.Views.Job
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.BI.Extensions;
    using Disco.Models.Repository;
    using Disco.Web;
    using Disco.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Job/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<Disco.Web.Models.Job.IndexModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Job\Index.cshtml"
  
    ViewBag.Title = "Jobs";
    Html.BundleDeferred("~/ClientScripts/Modules/Highcharts");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"clearfix columnHost\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"column50\"");

WriteLiteral(">\r\n        <h2>Search Jobs</h2>\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\Job\Index.cshtml"
   Write(Html.Partial(MVC.Shared.Views._SearchDialog, "jobs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"column50\"");

WriteLiteral(">\r\n        <h2>Daily Opened &amp; Closed Jobs</h2>\r\n        <div");

WriteLiteral(" id=\"chartHostJobDailyOpenedClosed\"");

WriteLiteral(" style=\"height: 175px;\"");

WriteLiteral(">\r\n        </div>\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            (function () {\r\n\r\n                var chartData;\r\n\r\n              " +
"  function buildChart() {\r\n                    $(function () {\r\n\r\n              " +
"          var data = chartData;\r\n\r\n                        var dataTotalOpenJobs" +
" = [];\r\n                        var dataOpenedJobs = [];\r\n                      " +
"  var dataClosedJobs = [];\r\n                        for (var i = 0; i < data.len" +
"gth; i++) {\r\n                            var dataItem = data[i];\r\n              " +
"              var dataItemDate = new Date(parseInt(dataItem.Timestamp.substr(6, " +
"dataItem.Timestamp.length - 8))).getTime(); // $.datepicker.parseDate(\'yy-mm-dd\'" +
", dataItem.Timestamp.substr(0, 10)).getTime();\r\n                            data" +
"TotalOpenJobs.push([dataItemDate, dataItem.TotalJobs]);\r\n                       " +
"     dataOpenedJobs.push([dataItemDate, dataItem.OpenedJobs]);\r\n                " +
"            dataClosedJobs.push([dataItemDate, dataItem.ClosedJobs]);\r\n         " +
"               }\r\n                        Highcharts.setOptions({\r\n             " +
"               global: {\r\n                                useUTC: false\r\n       " +
"                     }\r\n                        });\r\n                        new" +
" Highcharts.Chart({\r\n                            chart: {\r\n                     " +
"           renderTo: \'chartHostJobDailyOpenedClosed\',\r\n                         " +
"       height: 175,\r\n                                animation: false\r\n         " +
"                   },\r\n                            colors: [\'#BBBBBB\', \'#005fab\'" +
", \'#DB761D\'],\r\n                            title: {\r\n                           " +
"     text: null\r\n                            },\r\n                            plo" +
"tOptions: {\r\n                                series: {\r\n                        " +
"            marker: {\r\n                                        radius: 3\r\n      " +
"                              },\r\n                                    animation:" +
" false\r\n                                }\r\n                            },\r\n     " +
"                       legend: {\r\n                                align: \'left\'," +
"\r\n                                verticalAlign: \'top\',\r\n                       " +
"         y: 0,\r\n                                floating: true,\r\n               " +
"                 borderWidth: 0\r\n                            },\r\n               " +
"             xAxis: {\r\n                                type: \'datetime\',\r\n      " +
"                          tickInterval: 7 * 24 * 3600 * 1000, // week\r\n         " +
"                       tickWidth: 1,\r\n                                gridLineWi" +
"dth: 1,\r\n                                dateTimeLabelFormats: {\r\n              " +
"                      week: \'%e %b\'\r\n                                }\r\n        " +
"                    },\r\n                            yAxis: [{\r\n                 " +
"               title: {\r\n                                    text: null\r\n       " +
"                         },\r\n                                labels: {\r\n        " +
"                            enabled: false\r\n                                },\r\n" +
"                                min: 0\r\n                            }, {\r\n      " +
"                          title: {\r\n                                    text: nu" +
"ll\r\n                                },\r\n                                labels: " +
"{\r\n                                    enabled: false\r\n                         " +
"       },\r\n                                min: 0\r\n                            }" +
"],\r\n                            series: [{\r\n                                name" +
": \'Total Open Jobs\',\r\n                                data: dataTotalOpenJobs,\r\n" +
"                                yAxis: 1\r\n                            }, {\r\n    " +
"                            name: \'Closed Jobs\',\r\n                              " +
"  data: dataClosedJobs\r\n                            }, {\r\n                      " +
"          name: \'Opened Jobs\',\r\n                                data: dataOpened" +
"Jobs\r\n                            }],\r\n                            credits: {\r\n " +
"                               enabled: false\r\n                            }\r\n  " +
"                      });\r\n                    });\r\n                }\r\n\r\n\r\n     " +
"           $.getJSON(\'");

            
            #line 110 "..\..\Views\Job\Index.cshtml"
                       Write(Url.Action(MVC.API.Job.StatisticsDailyOpenedClosed()));

            
            #line default
            #line hidden
WriteLiteral("\', function (data) {\r\n                    chartData = data;\r\n                    " +
"buildChart();\r\n                });\r\n            }());\r\n\r\n        </script>\r\n    " +
"</div>\r\n</div>\r\n<h2>Open Jobs Awaiting Technician Action (");

            
            #line 119 "..\..\Views\Job\Index.cshtml"
                                     Write(Model.OpenJobs.Items.Count);

            
            #line default
            #line hidden
WriteLiteral(")</h2>\r\n");

            
            #line 120 "..\..\Views\Job\Index.cshtml"
Write(Html.Partial(MVC.Shared.Views._JobTable, Model.OpenJobs, new ViewDataDictionary()));

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Long Running Jobs (");

            
            #line 121 "..\..\Views\Job\Index.cshtml"
                  Write(Model.LongRunningJobs.Items.Count);

            
            #line default
            #line hidden
WriteLiteral(")</h2>\r\n");

            
            #line 122 "..\..\Views\Job\Index.cshtml"
Write(Html.Partial(MVC.Shared.Views._JobTable, Model.LongRunningJobs, new ViewDataDictionary()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
