#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco.Web.Views.Job.JobParts
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco;
    using Disco.BI.Extensions;
    using Disco.Models.Repository;
    using Disco.Services;
    using Disco.Services.Authorization;
    using Disco.Services.Web;
    using Disco.Web;
    using Disco.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Job/JobParts/Insurance.cshtml")]
    public partial class Insurance : Disco.Services.Web.WebViewPage<Disco.Web.Models.Job.ShowModel>
    {
        public Insurance()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Job\JobParts\Insurance.cshtml"
  
    Authorization.Require(Claims.Job.ShowNonWarrantyInsurance);

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" id=\"jobNonWarrantyInsurance\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Job\JobParts\Insurance.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Job\JobParts\Insurance.cshtml"
     if (Model.Job.JobMetaNonWarranty.IsInsuranceClaim)
    {
        if (Authorization.Has(Claims.Job.Properties.NonWarrantyProperties.InsuranceDetails))
        {
            Html.BundleDeferred("~/ClientScripts/Modules/Disco-PropertyChangeHelpers");

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 230px;\"");

WriteLiteral(">Date of Loss or Damage\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.LossOrDamageDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        var dateField = $('#Job_JobMetaInsurance_LossOrDamageDate');
                        document.DiscoFunctions.DateChangeHelper(
                        dateField,
                        'Unknown',
                        '");

            
            #line 23 "..\..\Views\Job\JobParts\Insurance.cshtml"
                     Write(Url.Action(MVC.API.Job.UpdateInsuranceLossOrDamageDate(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                        \'LossOrDamageDate\',\r\n                        null\r\n  " +
"                      );\r\n                    });\r\n                </script>\r\n  " +
"          </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Event Location\r\n            </th>\r\n            <td>" +
"\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.EventLocation));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                    $(function () {\r\n                        document.DiscoFun" +
"ctions.PropertyChangeHelper(\r\n                            $(\'#Job_JobMetaInsuran" +
"ce_EventLocation\'),\r\n                            \'Unknown\',\r\n                   " +
"         \'");

            
            #line 43 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceEventLocation(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'EventLocation\'\r\n                        );\r\n    " +
"                });\r\n                </script>\r\n            </td>\r\n        </tr>" +
"\r\n");

WriteLiteral("        <tr>\r\n            <th>Description\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                    $(function () {\r\n                        document.DiscoFun" +
"ctions.PropertyChangeHelper(\r\n                            $(\'#Job_JobMetaInsuran" +
"ce_Description\'),\r\n                            \'None\',\r\n                        " +
"    \'");

            
            #line 62 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceDescription(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'Description\'\r\n                        );\r\n      " +
"              });\r\n                </script>\r\n            </td>\r\n        </tr>\r\n" +
"");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">&nbsp;\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 73 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.ThirdPartyCaused));

            
            #line default
            #line hidden
            
            #line 73 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                        Write(Html.LabelFor(m => m.Job.JobMetaInsurance.ThirdPartyCaused));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 74 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 75 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" id=\"Job_JobMetaInsurance_ThirdPartyCaused_Details\"");

WriteLiteral(" style=\"padding-left: 25px;\"");

WriteLiteral(">\r\n                    <div>\r\n                        <h5>Third Party Name</h5>\r\n" +
"");

WriteLiteral("                        ");

            
            #line 79 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.EditorFor(m => m.Job.JobMetaInsurance.ThirdPartyCausedName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 80 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 81 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<h5>Why Third Parties Fault</h5>\r\n");

WriteLiteral("                        ");

            
            #line 85 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.EditorFor(m => m.Job.JobMetaInsurance.ThirdPartyCausedWhy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 86 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 87 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        var thirdPartyField = $('#Job_JobMetaInsurance_ThirdPartyCaused');
                        var thirdPartyDetails = $('#Job_JobMetaInsurance_ThirdPartyCaused_Details');
                        var thirdPartyDetails_Changed = function (e, dontAnimate) {
                            if (thirdPartyField.is(':checked')) {
                                if (dontAnimate) {
                                    thirdPartyDetails.show();
                                } else {
                                    thirdPartyDetails.slideDown();
                                }
                            } else {
                                if (dontAnimate) {
                                    thirdPartyDetails.hide();
                                } else {
                                    thirdPartyDetails.slideUp();
                                }
                            }
                        };
                        thirdPartyDetails_Changed(null, true);
                        thirdPartyField.change(thirdPartyDetails_Changed);

                        document.DiscoFunctions.PropertyChangeHelper(
                            thirdPartyField,
                            null,
                            '");

            
            #line 115 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceThirdPartyCaused(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral(@"',
                            'ThirdPartyCaused'
                        );
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_ThirdPartyCausedName'),
                            'None',
                            '");

            
            #line 121 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceThirdPartyCausedName(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral(@"',
                            'ThirdPartyCausedName'
                        );
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_ThirdPartyCausedWhy'),
                            'Unknown',
                            '");

            
            #line 127 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceThirdPartyCausedWhy(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'ThirdPartyCausedWhy\'\r\n                        );" +
"\r\n                    });\r\n                </script>\r\n            </td>\r\n       " +
" </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Witnessed by (Name/Address)\r\n            </th>\r\n   " +
"         <td>\r\n");

WriteLiteral("                ");

            
            #line 138 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.WitnessesNamesAddresses));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 139 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 140 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_WitnessesNamesAddresses'),
                            'None',
                            '");

            
            #line 146 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceWitnessesNamesAddresses(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'WitnessesNamesAddresses\'\r\n                      " +
"  );\r\n                    });\r\n                </script>\r\n            </td>\r\n   " +
"     </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Burglary/Theft - Method of Entry\r\n            </th>" +
"\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 157 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.BurglaryTheftMethodOfEntry));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 158 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 159 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_BurglaryTheftMethodOfEntry'),
                            'None',
                            '");

            
            #line 165 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceBurglaryTheftMethodOfEntry(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'BurglaryTheftMethodOfEntry\'\r\n                   " +
"     );\r\n                    });\r\n                </script>\r\n            </td>\r\n" +
"        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">Property Last Seen\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 176 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.PropertyLastSeenDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 177 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        var dateField = $('#Job_JobMetaInsurance_PropertyLastSeenDate');
                        document.DiscoFunctions.DateChangeHelper(
                        dateField,
                        'Unknown/NA',
                        '");

            
            #line 184 "..\..\Views\Job\JobParts\Insurance.cshtml"
                     Write(Url.Action(MVC.API.Job.UpdateInsurancePropertyLastSeenDate(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                        \'PropertyLastSeenDate\',\r\n                        null" +
"\r\n                        );\r\n                    });\r\n                </script>" +
"\r\n            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">&nbsp;\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 196 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.PoliceNotified));

            
            #line default
            #line hidden
            
            #line 196 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                      Write(Html.LabelFor(m => m.Job.JobMetaInsurance.PoliceNotified));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 197 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 198 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" id=\"Job_JobMetaInsurance_PoliceNotified_Details\"");

WriteLiteral(" style=\"padding-left: 25px;\"");

WriteLiteral(">\r\n                    <div>\r\n                        <h5>Station</h5>\r\n");

WriteLiteral("                        ");

            
            #line 202 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.EditorFor(m => m.Job.JobMetaInsurance.PoliceNotifiedStation));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 203 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 204 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<h5>Date</h5>\r\n");

WriteLiteral("                        ");

            
            #line 208 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.EditorFor(m => m.Job.JobMetaInsurance.PoliceNotifiedDate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 209 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div>\r\n                        " +
"<h5>Crime Report #</h5>\r\n");

WriteLiteral("                        ");

            
            #line 213 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.EditorFor(m => m.Job.JobMetaInsurance.PoliceNotifiedCrimeReportNo));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 214 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 215 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        var policeNotifiedField = $('#Job_JobMetaInsurance_PoliceNotified');
                        var policeNotifiedDetails = $('#Job_JobMetaInsurance_PoliceNotified_Details');
                        var policeNotifiedDetails_Changed = function (e, dontAnimate) {
                            if (policeNotifiedField.is(':checked')) {
                                if (dontAnimate) {
                                    policeNotifiedDetails.show();
                                } else {
                                    policeNotifiedDetails.slideDown();
                                }
                            } else {
                                if (dontAnimate) {
                                    policeNotifiedDetails.hide();
                                } else {
                                    policeNotifiedDetails.slideUp();
                                }
                            }
                        };
                        policeNotifiedDetails_Changed(null, true);
                        policeNotifiedField.change(policeNotifiedDetails_Changed);

                        document.DiscoFunctions.PropertyChangeHelper(
                            policeNotifiedField,
                            null,
                            '");

            
            #line 243 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsurancePoliceNotified(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral(@"',
                            'PoliceNotified'
                        );
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_PoliceNotifiedStation'),
                            'Unknown',
                            '");

            
            #line 249 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsurancePoliceNotifiedStation(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral(@"',
                            'PoliceNotifiedStation'
                        );
                        var dateField = $('#Job_JobMetaInsurance_PoliceNotifiedDate');
                        document.DiscoFunctions.DateChangeHelper(
                        dateField,
                        'Unknown',
                        '");

            
            #line 256 "..\..\Views\Job\JobParts\Insurance.cshtml"
                     Write(Url.Action(MVC.API.Job.UpdateInsurancePoliceNotifiedDate(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral(@"',
                        'PoliceNotifiedDate',
                        null,
                        true
                        );
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_PoliceNotifiedCrimeReportNo'),
                            'Unknown',
                            '");

            
            #line 264 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsurancePoliceNotifiedCrimeReportNo(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'PoliceNotifiedCrimeReportNo\'\r\n                  " +
"      );\r\n                    });\r\n                </script>\r\n            </td>\r" +
"\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Action to Recover/Reduce Loss\r\n            </th>\r\n " +
"           <td>\r\n");

WriteLiteral("                ");

            
            #line 275 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.RecoverReduceAction));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 276 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 277 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                    $(function () {\r\n                        document.DiscoFun" +
"ctions.PropertyChangeHelper(\r\n                            $(\'#Job_JobMetaInsuran" +
"ce_RecoverReduceAction\'),\r\n                            \'None\',\r\n                " +
"            \'");

            
            #line 283 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceRecoverReduceAction(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'RecoverReduceAction\'\r\n                        );" +
"\r\n                    });\r\n                </script>\r\n            </td>\r\n       " +
" </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Other Interested Parties\r\n            </th>\r\n      " +
"      <td>\r\n");

WriteLiteral("                ");

            
            #line 294 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.OtherInterestedParties));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 295 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxSave());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 296 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        document.DiscoFunctions.PropertyChangeHelper(
                            $('#Job_JobMetaInsurance_OtherInterestedParties'),
                            'None',
                            '");

            
            #line 302 "..\..\Views\Job\JobParts\Insurance.cshtml"
                        Write(Url.Action(MVC.API.Job.UpdateInsuranceOtherInterestedParties(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                            \'OtherInterestedParties\'\r\n                       " +
" );\r\n                    });\r\n                </script>\r\n            </td>\r\n    " +
"    </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">Date of Purchase\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 313 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(Html.EditorFor(m => m.Job.JobMetaInsurance.DateOfPurchase));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 314 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(AjaxHelpers.AjaxLoader());

            
            #line default
            #line hidden
WriteLiteral("\r\n                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                    $(function () {
                        var dateField = $('#Job_JobMetaInsurance_DateOfPurchase');
                        document.DiscoFunctions.DateChangeHelper(
                        dateField,
                        'Unknown',
                        '");

            
            #line 321 "..\..\Views\Job\JobParts\Insurance.cshtml"
                     Write(Url.Action(MVC.API.Job.UpdateInsuranceDateOfPurchase(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                        \'DateOfPurchase\',\r\n                        null,\r\n   " +
"                     true\r\n                        );\r\n                    });\r\n" +
"                </script>\r\n            </td>\r\n        </tr>\r\n");

            
            #line 330 "..\..\Views\Job\JobParts\Insurance.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 230px;\"");

WriteLiteral(">Date of Loss or Damage\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 337 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(CommonHelpers.FriendlyDate(Model.Job.JobMetaInsurance.LossOrDamageDate, "Unknown", null));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Event Location\r\n            </th>\r\n            <td>" +
"\r\n");

            
            #line 344 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 344 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.EventLocation))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown/None&gt;</span>\r\n");

            
            #line 347 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 350 "..\..\Views\Job\JobParts\Insurance.cshtml"
               Write(Model.Job.JobMetaInsurance.EventLocation);

            
            #line default
            #line hidden
            
            #line 350 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                             
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Description\r\n            </th>\r\n            <td>\r\n");

            
            #line 358 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 358 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.Description))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;None&gt;</span>\r\n");

            
            #line 361 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 364 "..\..\Views\Job\JobParts\Insurance.cshtml"
               Write(Model.Job.JobMetaInsurance.Description);

            
            #line default
            #line hidden
            
            #line 364 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                           
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">Caused by Third Party\r\n            </th>\r\n            <td>\r\n");

            
            #line 372 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 372 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (Model.Job.JobMetaInsurance.ThirdPartyCaused)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"Job_JobMetaInsurance_ThirdPartyCaused_Details\"");

WriteLiteral(" style=\"padding-left: 25px;\"");

WriteLiteral(">\r\n                        <div>\r\n                            <h5>Third Party Nam" +
"e</h5>\r\n");

            
            #line 377 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 377 "..\..\Views\Job\JobParts\Insurance.cshtml"
                             if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.ThirdPartyCausedName))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown&gt;</span>\r\n");

            
            #line 380 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 383 "..\..\Views\Job\JobParts\Insurance.cshtml"
                           Write(Model.Job.JobMetaInsurance.ThirdPartyCausedName);

            
            #line default
            #line hidden
            
            #line 383 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                                
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                        <div>\r\n                  " +
"          <h5>Why Third Parties Fault</h5>\r\n");

            
            #line 388 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 388 "..\..\Views\Job\JobParts\Insurance.cshtml"
                             if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.ThirdPartyCausedWhy))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown&gt;</span>\r\n");

            
            #line 391 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 394 "..\..\Views\Job\JobParts\Insurance.cshtml"
                           Write(Model.Job.JobMetaInsurance.ThirdPartyCausedWhy);

            
            #line default
            #line hidden
            
            #line 394 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                               
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n");

            
            #line 398 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Not Caused by Third Party&gt;</span>\r\n");

            
            #line 402 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Witnessed by (Name/Address)\r\n            </th>\r\n   " +
"         <td>\r\n");

            
            #line 409 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 409 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.WitnessesNamesAddresses))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown/None&gt;</span>\r\n");

            
            #line 412 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 415 "..\..\Views\Job\JobParts\Insurance.cshtml"
               Write(Model.Job.JobMetaInsurance.WitnessesNamesAddresses);

            
            #line default
            #line hidden
            
            #line 415 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                       
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Burglary/Theft - Method of Entry\r\n            </th>" +
"\r\n            <td>\r\n");

            
            #line 423 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 423 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.BurglaryTheftMethodOfEntry))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown/None&gt;</span>\r\n");

            
            #line 426 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 429 "..\..\Views\Job\JobParts\Insurance.cshtml"
               Write(Model.Job.JobMetaInsurance.BurglaryTheftMethodOfEntry);

            
            #line default
            #line hidden
            
            #line 429 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                          
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">Property Last Seen\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 437 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(CommonHelpers.FriendlyDate(Model.Job.JobMetaInsurance.PropertyLastSeenDate, "Unknown", null));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">&nbsp;\r\n            Police Notified\r\n            </th>\r\n            <td>\r\n");

            
            #line 445 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 445 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (Model.Job.JobMetaInsurance.PoliceNotified)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" id=\"Job_JobMetaInsurance_PoliceNotified_Details\"");

WriteLiteral(" style=\"padding-left: 25px;\"");

WriteLiteral(">\r\n                        <div>\r\n                            <h5>Station</h5>\r\n");

            
            #line 450 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 450 "..\..\Views\Job\JobParts\Insurance.cshtml"
                             if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.PoliceNotifiedStation))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown&gt;</span>\r\n");

            
            #line 453 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 456 "..\..\Views\Job\JobParts\Insurance.cshtml"
                           Write(Model.Job.JobMetaInsurance.PoliceNotifiedStation);

            
            #line default
            #line hidden
            
            #line 456 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                                 
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                        <div>\r\n                  " +
"          <h5>Date</h5>\r\n");

WriteLiteral("                            ");

            
            #line 461 "..\..\Views\Job\JobParts\Insurance.cshtml"
                       Write(CommonHelpers.FriendlyDate(Model.Job.JobMetaInsurance.PoliceNotifiedDate, "Unknown", null));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                        <div>\r\n                " +
"            <h5>Crime Report #</h5>\r\n");

            
            #line 465 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 465 "..\..\Views\Job\JobParts\Insurance.cshtml"
                             if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.PoliceNotifiedCrimeReportNo))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown&gt;</span>\r\n");

            
            #line 468 "..\..\Views\Job\JobParts\Insurance.cshtml"
                            }
                            else
                            {
                                
            
            #line default
            #line hidden
            
            #line 471 "..\..\Views\Job\JobParts\Insurance.cshtml"
                           Write(Model.Job.JobMetaInsurance.PoliceNotifiedCrimeReportNo);

            
            #line default
            #line hidden
            
            #line 471 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                                       
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n");

            
            #line 475 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Not Notified&gt;</span>\r\n");

            
            #line 479 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Action to Recover/Reduce Loss\r\n            </th>\r\n " +
"           <td>\r\n");

            
            #line 486 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 486 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.RecoverReduceAction))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown/None&gt;</span>\r\n");

            
            #line 489 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 492 "..\..\Views\Job\JobParts\Insurance.cshtml"
               Write(Model.Job.JobMetaInsurance.RecoverReduceAction);

            
            #line default
            #line hidden
            
            #line 492 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                   
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th>Other Interested Parties\r\n            </th>\r\n      " +
"      <td>\r\n");

            
            #line 500 "..\..\Views\Job\JobParts\Insurance.cshtml"
                
            
            #line default
            #line hidden
            
            #line 500 "..\..\Views\Job\JobParts\Insurance.cshtml"
                 if (string.IsNullOrWhiteSpace(Model.Job.JobMetaInsurance.OtherInterestedParties))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">&lt;Unknown/None&gt;</span>\r\n");

            
            #line 503 "..\..\Views\Job\JobParts\Insurance.cshtml"
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 506 "..\..\Views\Job\JobParts\Insurance.cshtml"
               Write(Model.Job.JobMetaInsurance.OtherInterestedParties);

            
            #line default
            #line hidden
            
            #line 506 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                      
                }

            
            #line default
            #line hidden
WriteLiteral("            </td>\r\n        </tr>\r\n");

WriteLiteral("        <tr>\r\n            <th");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(">Date of Purchase\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 514 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(CommonHelpers.FriendlyDate(Model.Job.JobMetaInsurance.DateOfPurchase, "Unknown", null));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

            
            #line 517 "..\..\Views\Job\JobParts\Insurance.cshtml"
        }
        if (Authorization.Has(Claims.Job.Properties.NonWarrantyProperties.InsuranceClaimFormSent))
        {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <th>Claim Form Sent Date\r\n            </th>\r\n          " +
"  <td>\r\n");

WriteLiteral("                ");

            
            #line 524 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(CommonHelpers.FriendlyDate(Model.Job.JobMetaInsurance.ClaimFormSentDate, "Not Sent", "Job_JobMetaInsurance_ClaimFormSentDate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" id=\"Job_JobMetaInsurance_ClaimFormSentUserId\"");

WriteLiteral(">");

            
            #line 525 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                Write(string.IsNullOrEmpty(Model.Job.JobMetaInsurance.ClaimFormSentUserId) ? string.Empty : string.Format("by {0}", Model.Job.JobMetaInsurance.ClaimFormSentUser.ToString()));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <script>\r\n                    $(function () {\r\n         " +
"               var updateUrl = \'");

            
            #line 528 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                     Write(Url.Action(MVC.API.Job.Update(Model.Job.Id, null)));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n                        var jobOpenDate = \'");

            
            #line 529 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                       Write(Model.Job.OpenedDate.ToISO8601());

            
            #line default
            #line hidden
WriteLiteral(@"';

                        document.DiscoFunctions.DateDialogCreateUpdater(updateUrl, 'Claim Form Sent Date', 'Job_JobMetaInsurance_ClaimFormSentDate', 'Job_JobMetaInsurance_ClaimFormSentUserId', 'InsuranceClaimFormSentDate', 'Not Sent', jobOpenDate, false);
                    });
                </script>
            </td>
        </tr>
");

            
            #line 536 "..\..\Views\Job\JobParts\Insurance.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <th>Claim Form Sent Date\r\n            </th>\r\n          " +
"  <td>\r\n");

WriteLiteral("                ");

            
            #line 543 "..\..\Views\Job\JobParts\Insurance.cshtml"
           Write(CommonHelpers.FriendlyDate(Model.Job.JobMetaInsurance.ClaimFormSentDate, "Not Sent", "Job_JobMetaInsurance_ClaimFormSentDate"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" id=\"Job_JobMetaInsurance_ClaimFormSentUserId\"");

WriteLiteral(">");

            
            #line 544 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                Write(string.IsNullOrEmpty(Model.Job.JobMetaInsurance.ClaimFormSentUserId) ? string.Empty : string.Format("by {0}", Model.Job.JobMetaInsurance.ClaimFormSentUser.ToString()));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n        </tr>\r\n");

            
            #line 547 "..\..\Views\Job\JobParts\Insurance.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 549 "..\..\Views\Job\JobParts\Insurance.cshtml"
     if (Authorization.Has(Claims.Job.Properties.NonWarrantyProperties.IsInsuranceClaim))
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <th>Insurance Claim\r\n            </th>\r\n            <td" +
">\r\n                <div");

WriteLiteral(" style=\"padding: 8px; text-align: center\"");

WriteLiteral(">\r\n");

            
            #line 556 "..\..\Views\Job\JobParts\Insurance.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 556 "..\..\Views\Job\JobParts\Insurance.cshtml"
                     if (Model.Job.JobMetaNonWarranty.IsInsuranceClaim)
                    {
                        
            
            #line default
            #line hidden
            
            #line 558 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.ActionLinkButton("Remove Insurance Claim", MVC.API.Job.UpdateNonWarrantyIsInsuranceClaim(Model.Job.Id, false, true)));

            
            #line default
            #line hidden
            
            #line 558 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                                                                                                  
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 562 "..\..\Views\Job\JobParts\Insurance.cshtml"
                   Write(Html.ActionLinkButton("Add Insurance Claim", MVC.API.Job.UpdateNonWarrantyIsInsuranceClaim(Model.Job.Id, true, true)));

            
            #line default
            #line hidden
            
            #line 562 "..\..\Views\Job\JobParts\Insurance.cshtml"
                                                                                                                                              
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </td>\r\n        </tr>\r\n");

            
            #line 567 "..\..\Views\Job\JobParts\Insurance.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n");

        }
    }
}
#pragma warning restore 1591
