#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco.Web.Areas.Config.Views.DocumentTemplate
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco;
    using Disco.Models.Repository;
    using Disco.Services;
    using Disco.Services.Authorization;
    
    #line 2 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
    using Disco.Services.Interop.ActiveDirectory;
    
    #line default
    #line hidden
    using Disco.Services.Web;
    using Disco.Web;
    using Disco.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Config/Views/DocumentTemplate/_BulkGenerateShared.cshtml")]
    public partial class _BulkGenerateShared : Disco.Services.Web.WebViewPage<Disco.Web.Areas.Config.Models.DocumentTemplate.BulkGenerateModel>
    {
        public _BulkGenerateShared()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
  
    if (Model == null)
    {
        throw new ArgumentNullException("Model", "Model cannot be null.");
    }
    var userModel = Model as Disco.Web.Areas.Config.Models.DocumentTemplate.BulkGenerateUserModel;
    var deviceModel = Model as Disco.Web.Areas.Config.Models.DocumentTemplate.BulkGenerateDeviceModel;
    string scope;
    if (userModel != null)
    {
        scope = "user";
    }
    else if (deviceModel != null)
    {
        scope = "device";
    }
    else
    {
        throw new InvalidOperationException("Unexpected model: " + Model.GetType().FullName);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddUsers\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 818), Tuple.Create("\"", 877)
            
            #line 24 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                     , Tuple.Create(Tuple.Create("", 826), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 826), false)
, Tuple.Create(Tuple.Create("", 863), Tuple.Create(":", 863), true)
, Tuple.Create(Tuple.Create(" ", 864), Tuple.Create("Add", 865), true)
, Tuple.Create(Tuple.Create(" ", 868), Tuple.Create("by", 869), true)
, Tuple.Create(Tuple.Create(" ", 871), Tuple.Create("Users", 872), true)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n        <div>\r\n            Enter multiple <span");

WriteLiteral(" class=\"scopeDescBulkGenerate\"");

WriteLiteral(">User Ids</span> separated by <code>&lt;new line&gt;</code>, commas (<code>,</cod" +
"e>) or semicolons (<code>;</code>).\r\n        </div>\r\n");

            
            #line 29 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         if (userModel != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n                Security Groups can also be included. Members " +
"will be resolved and added.\r\n            </div>\r\n");

            
            #line 34 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 35 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         if (deviceModel != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n                Devices associated with the users will be adde" +
"d.\r\n            </div>\r\n");

            
            #line 40 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"examples clearfix\"");

WriteLiteral(">\r\n            <h4>Examples:</h4>\r\n            <div");

WriteLiteral(" class=\"example1 code\"");

WriteLiteral(">\r\n                user6<br />\r\n                smi0099<br />\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            Write(ActiveDirectory.Context.PrimaryDomain.NetBiosName);

            
            #line default
            #line hidden
WriteLiteral("\\rsmith<br />\r\n");

            
            #line 47 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 if (userModel != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("Domain Admins");

WriteLiteral("\r\n");

            
            #line 50 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"example2 code\"");

WriteLiteral(">\r\n                user6,smi0099,");

            
            #line 53 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                          Write(ActiveDirectory.Context.PrimaryDomain.NetBiosName);

            
            #line default
            #line hidden
WriteLiteral("\\rsmith\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"example3 code\"");

WriteLiteral(">\r\n                user6;smi0099;");

            
            #line 56 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                          Write(ActiveDirectory.Context.PrimaryDomain.NetBiosName);

            
            #line default
            #line hidden
WriteLiteral("\\rsmith\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 60 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
    
            
            #line default
            #line hidden
            
            #line 60 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
     using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddUsers()))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral(" data-valmsg-for=\"userIds\"");

WriteLiteral("></div>\r\n");

WriteLiteral("        <textarea");

WriteLiteral(" id=\"inputBulkGenerateDataIds\"");

WriteLiteral(" name=\"userIds\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"Identifiers are required\"");

WriteLiteral(" required></textarea>\r\n");

WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"scope\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2577), Tuple.Create("\"", 2591)
            
            #line 64 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 2585), Tuple.Create<System.Object, System.Int32>(scope
            
            #line default
            #line hidden
, 2585), false)
);

WriteLiteral(" />\r\n");

            
            #line 65 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 65 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

            
            #line 69 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (deviceModel != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddDevices\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2775), Tuple.Create("\"", 2836)
            
            #line 71 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                          , Tuple.Create(Tuple.Create("", 2783), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 2783), false)
, Tuple.Create(Tuple.Create("", 2820), Tuple.Create(":", 2820), true)
, Tuple.Create(Tuple.Create(" ", 2821), Tuple.Create("Add", 2822), true)
, Tuple.Create(Tuple.Create(" ", 2825), Tuple.Create("by", 2826), true)
, Tuple.Create(Tuple.Create(" ", 2828), Tuple.Create("Devices", 2829), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n            <div>\r\n                Enter multiple <span");

WriteLiteral(" class=\"scopeDescBulkGenerate\"");

WriteLiteral(">Device Serial Numbers</span> separated by <code>&lt;new line&gt;</code>, commas " +
"(<code>,</code>) or semicolons (<code>;</code>).\r\n            </div>\r\n          " +
"  <div");

WriteLiteral(" class=\"examples clearfix\"");

WriteLiteral(">\r\n                <h4>Examples:</h4>\r\n                <div");

WriteLiteral(" class=\"example1 code\"");

WriteLiteral(">\r\n                    LAPTOP-12345<br />\r\n                    TAB-987654<br />\r\n" +
"                    PHONE-ABC321\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"example2 code\"");

WriteLiteral(">\r\n                    LAPTOP-12345,TAB-987654,PHONE-ABC321\r\n                </di" +
"v>\r\n                <div");

WriteLiteral(" class=\"example3 code\"");

WriteLiteral(">\r\n                    LAPTOP-12345;TAB-987654;PHONE-ABC321\r\n                </di" +
"v>\r\n            </div>\r\n        </div>\r\n");

            
            #line 91 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddDevices()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral(" data-valmsg-for=\"userIds\"");

WriteLiteral("></div>\r\n");

WriteLiteral("            <textarea");

WriteLiteral(" name=\"deviceSerialNumbers\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"Identifiers are required\"");

WriteLiteral(" required></textarea>\r\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"scope\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4038), Tuple.Create("\"", 4052)
            
            #line 95 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 4046), Tuple.Create<System.Object, System.Int32>(scope
            
            #line default
            #line hidden
, 4046), false)
);

WriteLiteral(" />\r\n");

            
            #line 96 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 96 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 96 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 99 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 101 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (userModel != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddGroupMembers\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4254), Tuple.Create("\"", 4321)
            
            #line 103 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                               , Tuple.Create(Tuple.Create("", 4262), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 4262), false)
, Tuple.Create(Tuple.Create("", 4299), Tuple.Create(":", 4299), true)
, Tuple.Create(Tuple.Create(" ", 4300), Tuple.Create("Add", 4301), true)
, Tuple.Create(Tuple.Create(" ", 4304), Tuple.Create("by", 4305), true)
, Tuple.Create(Tuple.Create(" ", 4307), Tuple.Create("Group", 4308), true)
, Tuple.Create(Tuple.Create(" ", 4313), Tuple.Create("Members", 4314), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n            <div>\r\n                Add all members of a group (including recur" +
"sive members) to the bulk generation.\r\n            </div>\r\n        </div>\r\n");

            
            #line 109 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 109 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddGroupMembers()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <table");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n                <tbody>\r\n                    <tr>\r\n                        <th" +
">\r\n                            <label");

WriteLiteral(" for=\"DocumentTemplate_BulkGenerate_Dialog_AddGroupMembers_Group\"");

WriteLiteral(">Group:</label>\r\n                        </th>\r\n                        <td>\r\n   " +
"                         <input");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddGroupMembers_Group\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"groupId\"");

WriteLiteral(" data-autocomplete-src=\"");

            
            #line 118 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                 Write(Url.Action(MVC.API.System.SearchGroupSubjects()));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" required />\r\n                        </td>\r\n                    </tr>\r\n         " +
"       </tbody>\r\n            </table>\r\n");

            
            #line 123 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 123 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 123 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 126 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 128 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (userModel != null && userModel.UserFlags.Any(f => f.Count > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddUserFlag\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5458), Tuple.Create("\"", 5518)
            
            #line 130 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                           , Tuple.Create(Tuple.Create("", 5466), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 5466), false)
, Tuple.Create(Tuple.Create("", 5503), Tuple.Create(":", 5503), true)
, Tuple.Create(Tuple.Create(" ", 5504), Tuple.Create("Add", 5505), true)
, Tuple.Create(Tuple.Create(" ", 5508), Tuple.Create("User", 5509), true)
, Tuple.Create(Tuple.Create(" ", 5513), Tuple.Create("Flag", 5514), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n            <div>\r\n                Add all users associated with the flag to t" +
"he bulk generation.\r\n            </div>\r\n        </div>\r\n");

            
            #line 136 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 136 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddUserFlag()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"flagId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(">\r\n");

            
            #line 140 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 140 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 foreach (var flag in userModel.UserFlags)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5991), Tuple.Create("\"", 6042)
, Tuple.Create(Tuple.Create("", 5999), Tuple.Create("item", 5999), true)
            
            #line 142 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create(" ", 6003), Tuple.Create<System.Object, System.Int32>(flag.Count == 0 ? "disabled" : null
            
            #line default
            #line hidden
, 6004), false)
);

WriteLiteral(" data-userflagid=\"");

            
            #line 142 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                         Write(flag.Item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 6104), Tuple.Create("\"", 6173)
, Tuple.Create(Tuple.Create("", 6112), Tuple.Create("fa", 6112), true)
, Tuple.Create(Tuple.Create(" ", 6114), Tuple.Create("fa-", 6115), true)
            
            #line 143 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 6118), Tuple.Create<System.Object, System.Int32>(flag.Item.Icon
            
            #line default
            #line hidden
, 6118), false)
, Tuple.Create(Tuple.Create(" ", 6135), Tuple.Create("fa-fw", 6136), true)
, Tuple.Create(Tuple.Create(" ", 6141), Tuple.Create("fa-lg", 6142), true)
, Tuple.Create(Tuple.Create(" ", 6147), Tuple.Create("d-", 6148), true)
            
            #line 143 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 6150), Tuple.Create<System.Object, System.Int32>(flag.Item.IconColour
            
            #line default
            #line hidden
, 6150), false)
);

WriteLiteral("></i>");

            
            #line 143 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                Write(flag.Item.Name);

            
            #line default
            #line hidden
WriteLiteral(" <small>(");

            
            #line 143 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                        Write(flag.Count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 143 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                   Write(scope);

            
            #line default
            #line hidden
            
            #line 143 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                          Write(flag.Count == 1 ? null : "s");

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n                    </div>\r\n");

            
            #line 145 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

            
            #line 148 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 148 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 148 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 151 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 153 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (deviceModel != null && deviceModel.DeviceFlags.Any(f => f.Count > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddDeviceFlag\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 6592), Tuple.Create("\"", 6654)
            
            #line 155 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                             , Tuple.Create(Tuple.Create("", 6600), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 6600), false)
, Tuple.Create(Tuple.Create("", 6637), Tuple.Create(":", 6637), true)
, Tuple.Create(Tuple.Create(" ", 6638), Tuple.Create("Add", 6639), true)
, Tuple.Create(Tuple.Create(" ", 6642), Tuple.Create("Device", 6643), true)
, Tuple.Create(Tuple.Create(" ", 6649), Tuple.Create("Flag", 6650), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n            <div>\r\n                Add all devices associated with the flag to" +
" the bulk generation.\r\n            </div>\r\n        </div>\r\n");

            
            #line 161 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 161 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddDeviceFlag()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"flagId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(">\r\n");

            
            #line 165 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 165 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 foreach (var flag in deviceModel.DeviceFlags)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 7135), Tuple.Create("\"", 7186)
, Tuple.Create(Tuple.Create("", 7143), Tuple.Create("item", 7143), true)
            
            #line 167 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create(" ", 7147), Tuple.Create<System.Object, System.Int32>(flag.Count == 0 ? "disabled" : null
            
            #line default
            #line hidden
, 7148), false)
);

WriteLiteral(" data-userflagid=\"");

            
            #line 167 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                         Write(flag.Item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 7248), Tuple.Create("\"", 7317)
, Tuple.Create(Tuple.Create("", 7256), Tuple.Create("fa", 7256), true)
, Tuple.Create(Tuple.Create(" ", 7258), Tuple.Create("fa-", 7259), true)
            
            #line 168 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 7262), Tuple.Create<System.Object, System.Int32>(flag.Item.Icon
            
            #line default
            #line hidden
, 7262), false)
, Tuple.Create(Tuple.Create(" ", 7279), Tuple.Create("fa-fw", 7280), true)
, Tuple.Create(Tuple.Create(" ", 7285), Tuple.Create("fa-lg", 7286), true)
, Tuple.Create(Tuple.Create(" ", 7291), Tuple.Create("d-", 7292), true)
            
            #line 168 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 7294), Tuple.Create<System.Object, System.Int32>(flag.Item.IconColour
            
            #line default
            #line hidden
, 7294), false)
);

WriteLiteral("></i>");

            
            #line 168 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                Write(flag.Item.Name);

            
            #line default
            #line hidden
WriteLiteral(" <small>(");

            
            #line 168 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                        Write(flag.Count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 168 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                   Write(scope);

            
            #line default
            #line hidden
            
            #line 168 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                          Write(flag.Count == 1 ? null : "s");

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n                    </div>\r\n");

            
            #line 170 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

            
            #line 173 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 173 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 173 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 176 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 178 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (Model.DeviceProfiles.Any(b => b.Count > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddDeviceProfile\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7713), Tuple.Create("\"", 7781)
            
            #line 180 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                , Tuple.Create(Tuple.Create("", 7721), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 7721), false)
, Tuple.Create(Tuple.Create("", 7758), Tuple.Create(":", 7758), true)
, Tuple.Create(Tuple.Create(" ", 7759), Tuple.Create("Add", 7760), true)
, Tuple.Create(Tuple.Create(" ", 7763), Tuple.Create("by", 7764), true)
, Tuple.Create(Tuple.Create(" ", 7766), Tuple.Create("Device", 7767), true)
, Tuple.Create(Tuple.Create(" ", 7773), Tuple.Create("Profile", 7774), true)
);

WriteLiteral(">\r\n");

            
            #line 181 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 181 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         if (userModel != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n                <div>\r\n                    Add all users associated with a dev" +
"ice in the selected profile to the bulk generation.\r\n                </div>\r\n   " +
"         </div>\r\n");

            
            #line 188 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 189 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddDeviceProfile()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"deviceProfileId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(">\r\n");

            
            #line 193 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 193 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 foreach (var profile in Model.DeviceProfiles)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 8371), Tuple.Create("\"", 8425)
, Tuple.Create(Tuple.Create("", 8379), Tuple.Create("item", 8379), true)
            
            #line 195 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create(" ", 8383), Tuple.Create<System.Object, System.Int32>(profile.Count == 0 ? "disabled" : null
            
            #line default
            #line hidden
, 8384), false)
);

WriteLiteral(" data-id=\"");

            
            #line 195 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                    Write(profile.Item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-cog fa-fw fa-lg\"");

WriteLiteral("></i>");

            
            #line 196 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                        Write(profile.Item.Name);

            
            #line default
            #line hidden
WriteLiteral(" <small>(");

            
            #line 196 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                   Write(profile.Count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 196 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                 Write(scope);

            
            #line default
            #line hidden
            
            #line 196 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                        Write(profile.Count == 1 ? null : "s");

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n                    </div>\r\n");

            
            #line 198 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"scope\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8737), Tuple.Create("\"", 8751)
            
            #line 200 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 8745), Tuple.Create<System.Object, System.Int32>(scope
            
            #line default
            #line hidden
, 8745), false)
);

WriteLiteral(" />\r\n");

            
            #line 201 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 201 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 201 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 204 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 206 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (Model.DeviceBatches.Any(b => b.Count > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddDeviceBatch\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 8976), Tuple.Create("\"", 9042)
            
            #line 208 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                              , Tuple.Create(Tuple.Create("", 8984), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 8984), false)
, Tuple.Create(Tuple.Create("", 9021), Tuple.Create(":", 9021), true)
, Tuple.Create(Tuple.Create(" ", 9022), Tuple.Create("Add", 9023), true)
, Tuple.Create(Tuple.Create(" ", 9026), Tuple.Create("by", 9027), true)
, Tuple.Create(Tuple.Create(" ", 9029), Tuple.Create("Device", 9030), true)
, Tuple.Create(Tuple.Create(" ", 9036), Tuple.Create("Batch", 9037), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n            <div>\r\n                Add all users associated with a device in t" +
"he selected batch to the bulk generation.\r\n            </div>\r\n        </div>\r\n");

            
            #line 214 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 214 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddDeviceBatch()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"deviceBatchId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(">\r\n");

            
            #line 218 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 218 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 foreach (var batch in Model.DeviceBatches)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 9548), Tuple.Create("\"", 9600)
, Tuple.Create(Tuple.Create("", 9556), Tuple.Create("item", 9556), true)
            
            #line 220 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create(" ", 9560), Tuple.Create<System.Object, System.Int32>(batch.Count == 0 ? "disabled" : null
            
            #line default
            #line hidden
, 9561), false)
);

WriteLiteral(" data-id=\"");

            
            #line 220 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                  Write(batch.Item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-cog fa-fw fa-lg\"");

WriteLiteral("></i>");

            
            #line 221 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                        Write(batch.Item.Name);

            
            #line default
            #line hidden
WriteLiteral(" <small>(");

            
            #line 221 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                 Write(batch.Count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 221 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                             Write(scope);

            
            #line default
            #line hidden
            
            #line 221 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                    Write(batch.Count == 1 ? null : "s");

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n                    </div>\r\n");

            
            #line 223 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"scope\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9904), Tuple.Create("\"", 9918)
            
            #line 225 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 9912), Tuple.Create<System.Object, System.Int32>(scope
            
            #line default
            #line hidden
, 9912), false)
);

WriteLiteral(" />\r\n");

            
            #line 226 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 226 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 226 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 229 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 231 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (Model.DocumentTemplates.Any(b => b.Count > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddDocumentAttachment\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 10154), Tuple.Create("\"", 10227)
            
            #line 233 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    , Tuple.Create(Tuple.Create("", 10162), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 10162), false)
, Tuple.Create(Tuple.Create("", 10199), Tuple.Create(":", 10199), true)
, Tuple.Create(Tuple.Create(" ", 10200), Tuple.Create("Add", 10201), true)
, Tuple.Create(Tuple.Create(" ", 10204), Tuple.Create("by", 10205), true)
, Tuple.Create(Tuple.Create(" ", 10207), Tuple.Create("Document", 10208), true)
, Tuple.Create(Tuple.Create(" ", 10216), Tuple.Create("Attachment", 10217), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n            <div>\r\n                Add all users associated with an attachment" +
" of the selected document template to the bulk generation.\r\n            </div>\r\n" +
"        </div>\r\n");

            
            #line 239 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 239 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddDocumentAttachment()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"documentTemplateId\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(">\r\n");

            
            #line 243 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 243 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 foreach (var template in Model.DocumentTemplates)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 10769), Tuple.Create("\"", 10824)
, Tuple.Create(Tuple.Create("", 10777), Tuple.Create("item", 10777), true)
            
            #line 245 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create(" ", 10781), Tuple.Create<System.Object, System.Int32>(template.Count == 0 ? "disabled" : null
            
            #line default
            #line hidden
, 10782), false)
);

WriteLiteral(" data-id=\"");

            
            #line 245 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                     Write(template.Item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-file-text-o fa-fw fa-lg\"");

WriteLiteral("></i>");

            
            #line 246 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                Write(template.Item.Id);

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 246 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                   Write(template.Item.Description);

            
            #line default
            #line hidden
WriteLiteral(" <small>(");

            
            #line 246 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                      Write(template.Count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 246 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                     Write(scope);

            
            #line default
            #line hidden
            
            #line 246 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                                                            Write(template.Count == 1 ? null : "s");

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n                    </div>\r\n");

            
            #line 248 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"sub\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"DocumentTemplate_BulkGenerate_Dialog_AddDocumentAttachment_Threshold\"");

WriteLiteral(">Attachment Added After <small>(optional)</small></label>\r\n                <input" +
"");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddDocumentAttachment_Threshold\"");

WriteLiteral(" name=\"threshold\"");

WriteLiteral(" type=\"date\"");

WriteLiteral(" />\r\n            </div>\r\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"scope\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11511), Tuple.Create("\"", 11525)
            
            #line 254 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 11519), Tuple.Create<System.Object, System.Int32>(scope
            
            #line default
            #line hidden
, 11519), false)
);

WriteLiteral(" />\r\n");

            
            #line 255 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 255 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 255 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 258 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 260 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
 if (Model.UserDetails.Any(b => b.Count > 0))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddUserDetail\"");

WriteLiteral(" class=\"dialog dialog-bulk-generate\"");

WriteAttribute("title", Tuple.Create(" title=\"", 11747), Tuple.Create("\"", 11812)
            
            #line 262 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                            , Tuple.Create(Tuple.Create("", 11755), Tuple.Create<System.Object, System.Int32>(Model.DocumentTemplate.Description
            
            #line default
            #line hidden
, 11755), false)
, Tuple.Create(Tuple.Create("", 11792), Tuple.Create(":", 11792), true)
, Tuple.Create(Tuple.Create(" ", 11793), Tuple.Create("Add", 11794), true)
, Tuple.Create(Tuple.Create(" ", 11797), Tuple.Create("by", 11798), true)
, Tuple.Create(Tuple.Create(" ", 11800), Tuple.Create("User", 11801), true)
, Tuple.Create(Tuple.Create(" ", 11805), Tuple.Create("Detail", 11806), true)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"brief\"");

WriteLiteral(">\r\n");

            
            #line 264 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 264 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
             if (userModel != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div>\r\n                    Add all users with a matching user det" +
"ail to the bulk generation.\r\n                </div>\r\n");

            
            #line 269 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 270 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
             if (deviceModel != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div>\r\n                    Add all devices assigned to users with" +
" a matching user detail to the bulk generation.\r\n                </div>\r\n");

            
            #line 275 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 277 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
        
            
            #line default
            #line hidden
            
            #line 277 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateAddUserDetail()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"key\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

WriteLiteral("            <input");

WriteLiteral(" name=\"value\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" />\r\n");

            
            #line 281 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddUserDetail_Key\"");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(" style=\"width: 49%; float: left;\"");

WriteLiteral(">\r\n");

            
            #line 283 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                
            
            #line default
            #line hidden
            
            #line 283 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                 foreach (var key in Model.UserDetails)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 12731), Tuple.Create("\"", 12781)
, Tuple.Create(Tuple.Create("", 12739), Tuple.Create("item", 12739), true)
            
            #line 285 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create(" ", 12743), Tuple.Create<System.Object, System.Int32>(key.Count == 0 ? "disabled" : null
            
            #line default
            #line hidden
, 12744), false)
);

WriteLiteral(" data-id=\"");

            
            #line 285 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                Write(key.Item);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-info fa-fw fa-lg\"");

WriteLiteral("></i>");

            
            #line 286 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                         Write(key.Item.TrimEnd('*', '&'));

            
            #line default
            #line hidden
WriteLiteral(" <small>(");

            
            #line 286 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                             Write(key.Count.ToString("N0"));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 286 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                       Write(scope);

            
            #line default
            #line hidden
            
            #line 286 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                                                                                                              Write(key.Count == 1 ? null : "s");

            
            #line default
            #line hidden
WriteLiteral(")</small>\r\n                    </div>\r\n");

            
            #line 288 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

WriteLiteral("            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"scope\"");

WriteAttribute("value", Tuple.Create(" value=\"", 13088), Tuple.Create("\"", 13102)
            
            #line 290 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
, Tuple.Create(Tuple.Create("", 13096), Tuple.Create<System.Object, System.Int32>(scope
            
            #line default
            #line hidden
, 13096), false)
);

WriteLiteral(" />\r\n");

            
            #line 291 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 291 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 291 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 293 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerateGetUserDetailValues()))
        {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" name=\"key\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" required />\r\n");

            
            #line 296 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Dialog_AddUserDetail_Value\"");

WriteLiteral(" class=\"dialog-item-picker\"");

WriteLiteral(" style=\"width: 49%; float: left; margin-left: 1%;\"");

WriteLiteral(">\r\n            </div>\r\n");

            
            #line 299 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
            
            
            #line default
            #line hidden
            
            #line 299 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 299 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 302 "..\..\Areas\Config\Views\DocumentTemplate\_BulkGenerateShared.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
