#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco.Web.Areas.Config.Views.DocumentTemplate
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco;
    using Disco.Models.Repository;
    using Disco.Services;
    using Disco.Services.Authorization;
    using Disco.Services.Web;
    using Disco.Web;
    using Disco.Web.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Config/Views/DocumentTemplate/BulkGenerateDevice.cshtml")]
    public partial class BulkGenerateDevice : Disco.Services.Web.WebViewPage<Disco.Web.Areas.Config.Models.DocumentTemplate.BulkGenerateDeviceModel>
    {
        public BulkGenerateDevice()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
  
    Authorization.RequireAll(Claims.Config.DocumentTemplate.BulkGenerate, Claims.User.Actions.GenerateDocuments);

    ViewBag.Title = Html.ToBreadcrumb("Configuration", MVC.Config.Config.Index(), "Document Templates", MVC.Config.DocumentTemplate.Index(null), Model.DocumentTemplate.Description, MVC.Config.DocumentTemplate.Index(Model.DocumentTemplate.Id), "Bulk Generate");
    Html.BundleDeferred("~/ClientScripts/Modules/Disco-DocumentBulkGenerate");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
         using (Html.BeginForm(MVC.API.DocumentTemplate.BulkGenerate(Model.DocumentTemplate.Id)))
        {
            if (Model.TemplatePageCount > 1 && Model.TemplatePageCount % 2 != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <input");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_InsertBlankPage\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"InsertBlankPage\"");

WriteLiteral(" value=\"True\"");

WriteLiteral(" checked />");

WriteLiteral("<label");

WriteLiteral(" for=\"DocumentTemplate_BulkGenerate_InsertBlankPage\"");

WriteLiteral(">Insert Blank Pages for Double-Sided Printing</label>\r\n");

            
            #line 15 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_DataIds\"");

WriteLiteral(" name=\"DataIds\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" />\r\n");

WriteLiteral("            <button");

WriteLiteral(" id=\"BulkGenerate\"");

WriteLiteral(" class=\"button\"");

WriteLiteral(" disabled>Bulk Generate</button>\r\n");

            
            #line 18 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
            
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
                                    
        }

            
            #line default
            #line hidden
WriteLiteral("        <br />\r\n        <button");

WriteLiteral(" id=\"AddDevices\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add Devices</button>\r\n");

            
            #line 22 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
         if (Model.DeviceFlags.Any(f => f.Count > 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" id=\"AddDeviceFlag\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add With Device Flag</button>\r\n");

            
            #line 25 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 26 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
         if (Model.DeviceProfiles.Any(b => b.Count > 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" id=\"AddDeviceProfile\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add With Device Profile</button>\r\n");

            
            #line 29 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 30 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
         if (Model.DeviceBatches.Any(b => b.Count > 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" id=\"AddDeviceBatch\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add With Device Batch</button>\r\n");

            
            #line 33 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 34 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
         if (Model.DocumentTemplates.Any(b => b.Count > 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" id=\"AddDocumentAttachment\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add With Document Attachment</button>\r\n");

            
            #line 37 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <button");

WriteLiteral(" id=\"AddUsers\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add With Assigned Users</button>\r\n");

            
            #line 39 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
         if (Model.UserDetails.Any(b => b.Count > 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" id=\"AddUserDetail\"");

WriteLiteral(" class=\"button small\"");

WriteLiteral(">Add With Assigned User Detail</button>\r\n");

            
            #line 42 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <table");

WriteLiteral(" id=\"DocumentTemplate_BulkGenerate_Records\"");

WriteLiteral(" class=\"genericData\"");

WriteLiteral(" data-scope=\"device\"");

WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th>&nbsp;</th>\r\n          " +
"      <th>Serial Number</th>\r\n                <th");

WriteLiteral(" class=\"name\"");

WriteLiteral(">&nbsp;</th>\r\n                <th>Scope</th>\r\n            </tr>\r\n        </thead>" +
"\r\n        <tbody>\r\n            <tr");

WriteLiteral(" class=\"when-none\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(">Add Devices</td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n</div>\r\n\r\n");

            
            #line 61 "..\..\Areas\Config\Views\DocumentTemplate\BulkGenerateDevice.cshtml"
Write(Html.Partial(MVC.Config.DocumentTemplate.Views._BulkGenerateShared, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
